CREATE SCHEMA IF NOT EXISTS `groom` DEFAULT CHARACTER SET utf8mb4;

GRANT ALL ON *.* TO 'root'@'*' IDENTIFIED BY 'root' WITH GRANT OPTION;
GRANT ALL ON groom.* TO 'root'@'*';
FLUSH PRIVILEGES;

USE `groom`;