server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mariadb:3306/groom?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

# Hibernate
logging:
  level:
    com:
      querydsl: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        BasicBinder: TRACE

app:
  cors:
    # comma (',') seperated list of allowed origins for CORS
    allowed-origins: * 

jwt:
  secret-key: jwjdkalkjdsklsakdQWEFSDA3eas23dsakfaskd